name: jobby
description: JOBBY - Resume Analyzer & Candidate Matching System
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  file_picker: ^8.0.0
  syncfusion_flutter_pdf: ^25.1.35
  google_fonts: ^6.2.1
  fl_chart: ^0.68.0
  flutter_dotenv: ^5.1.0
  http: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/job_roles.json
    - assets/app_icon.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/app_icon.png