class JobRoles {
  static const Map<String, List<String>> roles = {
    "Data Scientist": [
      "Python",
      "R",
      "SQL",
      "Machine Learning",
      "Deep Learning",
      "Data Analysis",
      "Statistics",
      "TensorFlow",
      "Keras",
      "Scikit-learn",
      "Big Data",
      "Spark",
      "Data Visualization",
      "Pandas",
      "NumPy",
      "Data Wrangling",
      "Cloud Computing",
      "Model Deployment",
      "ML Ops",
      "Git",
      "Linux",
    ],
    "Business Analyst": [
      "Business Analysis",
      "Process Improvement",
      "SQL",
      "Excel",
      "Power BI",
      "Tableau",
      "Data Visualization",
      "Market Research",
      "Google Analytics",
      "Communication",
      "Problem Solving",
      "Hypothesis Testing",
      "A/B Testing",
    ],
    "Machine Learning Engineer": [
      "Python",
      "TensorFlow",
      "Keras",
      "PyTorch",
      "Machine Learning",
      "Deep Learning",
      "Model Deployment",
      "Cloud Computing",
      "Docker",
      "Kubernetes",
      "Data Engineering",
      "Feature Engineering",
      "Statistics",
      "ML Ops",
      "REST API",
      "Big Data",
      "Spark",
      "Git",
      "CI/CD",
    ],
    "UI/UX Designer": [
      "UI/UX Design",
      "Figma",
      "Adobe XD",
      "Sketch",
      "InDesign",
      "Photoshop",
      "Illustrator",
      "Graphic Design",
      "Branding",
      "Communication",
      "Attention to Detail",
    ],
    "Project Manager": [
      "Project Management",
      "Agile",
      "Scrum",
      "Kanban",
      "Leadership",
      "Communication",
      "Team Management",
      "Risk Management",
      "Strategic Planning",
      "Problem Solving",
      "Budgeting",
      "Change Management",
      "Decision Making",
      "Time Management",
    ],
    "DevOps Engineer": [
      "Linux",
      "Docker",
      "Kubernetes",
      "AWS",
      "Azure",
      "Google Cloud",
      "CI/CD",
      "Git",
      "Python",
      "Automation",
      "Cloud Computing",
    ],
    "Digital Marketer": [
      "Digital Marketing",
      "Social Media Marketing",
      "Content Marketing",
      "Email Marketing",
      "Google Analytics",
      "Marketing Strategy",
      "Copywriting",
      "Content Creation",
      "Communication",
    ],
  };

  static List<String> get roleNames => roles.keys.toList();
}
